### ISSUE TITLE
EPOCH varible not set in travis config

### ISSUE THREAD

**Issue by YuiYukihira** [allinone-com/Snowflake-generator#4]
**Describe the bug**
The EPOCH variable is not set correctly is the travis config, it needs fixing. The output from python is:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/snowflake/__main__.py", line 12, in <module>
    EPOCH = int(environ.get('EPOCH'))
ValueError: invalid literal for int() with base 10: ''
```

**To Reproduce**
1. Clone this repo
2. build in docker
3. run in similar fashion to travis config. e.g. `docker run -d -h snowflake-1 -p 8081:8080 -e "DEBUG=0,EPOCH=1546300800" --name snowflake-generator-off snowflake-generator`
4. get logs of container

**Expected behavior**
The EPOCH variable should be set, and the container should keep running.

**Comment by YuiYukihira** [comment]
This should now be fixed in #3, so I'm going to close this now.
